# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "75b8dd260ef0469d96d578705a87cffd0e09dab8"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "3627aeb7d4f6ade38f995d2c923e459146493c7e"

[[override]]
  name = "github.com/ericchiang/k8s"
  version = "v0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/kylelemons/godebug"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[override]]
  name = "github.com/ugorji/go"
  revision = "f1f1a805ed361a0e078bb537e4ea78cd37dcf065"
